import fs from "node:fs";
import path from "node:path";

const analysis = JSON.parse(fs.readFileSync("reports/extraction/missing-match-analysis.json", "utf8"));
const status = JSON.parse(fs.readFileSync("data/generated/extraction-status.json", "utf8"));
const effects = JSON.parse(fs.readFileSync("data/generated/effect-rows.json", "utf8")).rows;

function writeReport(relativePath, lines) {
  fs.mkdirSync(path.dirname(relativePath), { recursive: true });
  fs.writeFileSync(relativePath, `${lines.join("\n")}\n`, "utf8");
}

function countBy(rows, keyFn) {
  return rows.reduce((counts, row) => {
    const key = keyFn(row);
    counts[key] = (counts[key] ?? 0) + 1;
    return counts;
  }, {});
}

function markdownList(values) {
  return values.length ? values.map((value) => `  - ${value}`) : ["  - none"];
}

const autoCandidates = analysis.rows.flatMap((row) => (
  row.missingDiagnostics
    .filter((item) => item.autoMatchPossible)
    .map((item) => ({ ...item, characterId: row.characterId, displayName: row.displayName }))
));

writeReport("reports/extraction/auto-match-candidates.md", [
  "# Auto Match Candidates",
  "",
  "Generated by `node tools/analyze_missing_priority.mjs`.",
  "",
  "No automatic matching was applied. These are candidates only.",
  "",
  `- candidateCount: ${autoCandidates.length}`,
  "",
  ...autoCandidates.flatMap((item) => [
    `## ${item.displayName}`,
    "",
    `- characterId: ${item.characterId}`,
    `- missingType: ${item.missingType}`,
    "- attemptedSources:",
    ...markdownList(item.attemptedSources),
    "- closestCandidates:",
    ...markdownList(item.closestCandidates),
    `- whyAutoMatchPossible: ${item.failureReason === "source_exists_but_id_mismatch" ? "A source-side identity candidate exists, but current status rows did not match it to the stable characterId." : "A HoyoWiki entryPageId candidate exists, but the parser has not produced rows for this identity."}`,
    "- applied: false",
    "",
  ]),
]);

const effectTraceRows = analysis.rows
  .map((row) => {
    const items = row.missingDiagnostics.filter((item) => ["missing_effect_trace", "effect_rows_zero"].includes(item.missingType));
    if (!items.length) return null;
    const primary = items[0];
    let rootCause = "no_candidate_found";
    if (items.some((item) => item.failureReason === "parser_not_implemented")) rootCause = "parser_not_implemented";
    else if (items.some((item) => item.failureReason === "source_not_loaded")) rootCause = "source_not_loaded";
    else if (items.some((item) => item.needsCuratedSource)) rootCause = "curated_source_required";
    return {
      characterId: row.characterId,
      displayName: row.displayName,
      mergedMissingTypes: items.map((item) => item.missingType),
      rootCause,
      attemptedSources: [...new Set(items.flatMap((item) => item.attemptedSources))],
      closestCandidates: primary.closestCandidates,
      nextAction: primary.nextAction,
    };
  })
  .filter(Boolean);
const effectTraceRootCauseCounts = countBy(effectTraceRows, (row) => row.rootCause);

writeReport("reports/extraction/effect-trace-root-cause.md", [
  "# Effect Trace Root Cause",
  "",
  "Generated by `node tools/analyze_missing_priority.mjs`.",
  "",
  "`missing_effect_trace` and `effect_rows_zero` are merged per character when they point to the same missing effect trace cause.",
  "",
  "## Summary",
  "",
  `- raw effect_trace_not_found diagnostics: ${analysis.summary.failureReasonCounts.effect_trace_not_found ?? 0}`,
  `- dedupedCharacters: ${effectTraceRows.length}`,
  "",
  "## Root Cause Counts",
  "",
  ...Object.entries(effectTraceRootCauseCounts).sort((a, b) => a[0].localeCompare(b[0])).map(([key, value]) => `- ${key}: ${value}`),
  "",
  "## Character Rows",
  "",
  ...effectTraceRows.flatMap((row) => [
    `### ${row.displayName}`,
    "",
    `- characterId: ${row.characterId}`,
    `- mergedMissingTypes: ${row.mergedMissingTypes.join(", ")}`,
    `- rootCause: ${row.rootCause}`,
    "- attemptedSources:",
    ...markdownList(row.attemptedSources),
    "- closestCandidates:",
    ...markdownList(row.closestCandidates),
    `- nextAction: ${row.nextAction}`,
    "",
  ]),
]);

function dynamicType(effect) {
  const trace = String(effect.sourceTrace ?? "").toLowerCase();
  const stat = String(effect.stat ?? "").toLowerCase();
  if (trace.includes("debuffcount")) return "debuff count";
  if (trace.includes("stack") || trace.includes("stacks") || trace.includes("nobility") || trace.includes("ashenroast") || trace.includes("overcap")) return "stack count";
  if (stat === "speed" || trace.includes(":speed")) return "speed condition";
  if (trace.includes("sourcecombatatkratio") || trace.includes("selfenhancedskill") || ["followdamage", "ultimatedamage", "basicdamage", "combatskilldamage"].includes(stat)) return "attack type condition";
  if (effect.minEidolon != null || /:e[1-6]:/i.test(String(effect.sourceTrace ?? ""))) return "eidolon condition";
  if (trace.includes("other-nihility") || trace.includes("no-other-nihility") || trace.includes("party") || trace.includes("ally") || trace.includes("allies")) return "party condition";
  return "unknown";
}

const dynamicEffects = effects.filter((row) => row.valueMode === "dynamic_formula");
const statusById = new Map((status.rows ?? []).map((row) => [row.characterId, row]));
const dynamicDiagnostics = analysis.rows
  .filter((row) => row.missingDiagnostics.some((item) => item.failureReason === "valueMode_dynamic_formula_unresolved"))
  .map((row) => {
    const characterEffects = dynamicEffects.filter((effect) => {
      const statusRow = statusById.get(row.characterId);
      const identifiers = [
        row.characterId,
        statusRow?.internalName,
        statusRow?.identifiers?.effectAvatar,
        statusRow?.identifiers?.effectName,
        statusRow?.identifiers?.hoyowikiEntryPageId,
        statusRow?.identifiers?.coefficientAvatar,
        statusRow?.identifiers?.coefficientAvatarId,
      ].filter(Boolean).map(String);
      return identifiers.includes(String(effect.effectProviderId)) || identifiers.includes(String(effect.characterId));
    });
    const typeCounts = countBy(characterEffects, dynamicType);
    const primaryType = Object.entries(typeCounts).sort((left, right) => right[1] - left[1] || left[0].localeCompare(right[0]))[0]?.[0] ?? "unknown";
    return {
      characterId: row.characterId,
      displayName: row.displayName,
      primaryType,
      dynamicRows: characterEffects.map((effect) => ({
        id: effect.id,
        stat: effect.stat,
        effectType: effect.effectType,
        minEidolon: effect.minEidolon,
        sourceTrace: effect.sourceTrace,
        type: dynamicType(effect),
      })),
    };
  });
const dynamicCharacterCounts = countBy(dynamicDiagnostics, (row) => row.primaryType);
const dynamicRowCounts = countBy(dynamicEffects, dynamicType);

writeReport("reports/extraction/dynamic-formula-type-breakdown.md", [
  "# Dynamic Formula Type Breakdown",
  "",
  "Generated by `node tools/analyze_missing_priority.mjs`.",
  "",
  "No dynamic formula resolver was implemented. This report only splits blocked rows by likely resolver family.",
  "",
  "## Summary",
  "",
  `- characterLevelBlockedDiagnostics: ${dynamicDiagnostics.length}`,
  `- dynamicFormulaEffectRows: ${dynamicEffects.length}`,
  "",
  "## Character-Level Primary Type Counts",
  "",
  ...["debuff count", "stack count", "speed condition", "attack type condition", "eidolon condition", "party condition", "unknown"].map((key) => `- ${key}: ${dynamicCharacterCounts[key] ?? 0}`),
  "",
  "## Effect-Row Type Counts",
  "",
  ...["debuff count", "stack count", "speed condition", "attack type condition", "eidolon condition", "party condition", "unknown"].map((key) => `- ${key}: ${dynamicRowCounts[key] ?? 0}`),
  "",
  "## Character Rows",
  "",
  ...dynamicDiagnostics.flatMap((row) => [
    `### ${row.displayName}`,
    "",
    `- characterId: ${row.characterId}`,
    `- primaryType: ${row.primaryType}`,
    `- dynamicRows: ${row.dynamicRows.length}`,
    ...row.dynamicRows.map((effect) => `- ${effect.id}: type=${effect.type}; stat=${effect.stat}; minEidolon=${effect.minEidolon ?? "none"}; trace=${effect.sourceTrace}`),
    "",
  ]),
]);

const curatedByFailure = analysis.rows.flatMap((row) => (
  row.missingDiagnostics
    .filter((item) => item.failureReason === "curated_source_required")
    .map((item) => ({ ...item, characterId: row.characterId, displayName: row.displayName, basis: "failureReason" }))
));
const curatedByFlag = analysis.rows.flatMap((row) => (
  row.missingDiagnostics
    .filter((item) => item.needsCuratedSource)
    .map((item) => ({ ...item, characterId: row.characterId, displayName: row.displayName, basis: "needsCuratedSource" }))
));
const curatedByNextAction = analysis.rows.flatMap((row) => (
  row.missingDiagnostics
    .filter((item) => /curate|curated source|source-backed/i.test(item.nextAction))
    .map((item) => ({ ...item, characterId: row.characterId, displayName: row.displayName, basis: "nextAction" }))
));

writeReport("reports/extraction/curated-source-required-breakdown.md", [
  "# Curated Source Required Breakdown",
  "",
  "Generated by `node tools/analyze_missing_priority.mjs`.",
  "",
  "## Summary",
  "",
  `- failureReason curated_source_required: ${curatedByFailure.length}`,
  `- needsCuratedSource true: ${curatedByFlag.length}`,
  `- nextAction mentions curate/source-backed: ${curatedByNextAction.length}`,
  "",
  "## Basis Difference",
  "",
  "- `failureReason === curated_source_required`: the primary blocking reason is that no source-backed row is available for readiness.",
  "- `needsCuratedSource === true`: a broader flag. The failure reason can be more specific, but the next fix still needs source-backed or curated evidence.",
  "- `nextAction` basis: the broadest text-based count. It includes diagnostics whose action text mentions `curate`, `curated source`, or `source-backed`.",
  "",
  "## needsCuratedSource By Failure Reason",
  "",
  ...Object.entries(countBy(curatedByFlag, (item) => item.failureReason)).sort((a, b) => a[0].localeCompare(b[0])).map(([key, value]) => `- ${key}: ${value}`),
  "",
  "## failureReason curated_source_required Rows",
  "",
  ...curatedByFailure.flatMap((item) => [
    `### ${item.displayName}`,
    "",
    `- characterId: ${item.characterId}`,
    `- missingType: ${item.missingType}`,
    `- nextAction: ${item.nextAction}`,
    "",
  ]),
]);

console.log(JSON.stringify({
  autoMatchPossible: autoCandidates.length,
  effectTraceRootCauseCounts,
  dynamicCharacterCounts,
  dynamicRowCounts,
  curatedSourceRequired: {
    failureReason: curatedByFailure.length,
    needsCuratedSource: curatedByFlag.length,
    nextAction: curatedByNextAction.length,
  },
}, null, 2));
