import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

function readJson(relativePath) {
  return JSON.parse(fs.readFileSync(relativePath, "utf8"));
}

function readHeadJson(relativePath) {
  try {
    return JSON.parse(execFileSync("git", ["show", `HEAD:${relativePath}`], { encoding: "utf8" }));
  } catch {
    return null;
  }
}

function writeJson(relativePath, value) {
  fs.mkdirSync(path.dirname(relativePath), { recursive: true });
  fs.writeFileSync(relativePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function writeReport(relativePath, lines) {
  fs.mkdirSync(path.dirname(relativePath), { recursive: true });
  fs.writeFileSync(relativePath, `${lines.join("\n")}\n`, "utf8");
}

function countBy(rows, getKey) {
  return rows.reduce((counts, row) => {
    const key = getKey(row);
    counts[key] = (counts[key] ?? 0) + 1;
    return counts;
  }, {});
}

function summarizeReadiness(summary = {}) {
  return {
    ready: summary.ready ?? 0,
    partial: summary.partial ?? 0,
    blocked: summary.blocked ?? 0,
  };
}

function delta(current, previous) {
  if (previous == null) return null;
  return current - previous;
}

const status = readJson("data/generated/extraction-status.json");
const previousStatus = readHeadJson("data/generated/extraction-status.json");
const sourceRows = readJson("data/generated/source-rows.json").rows;
const effectRows = readJson("data/generated/effect-rows.json").rows;
const coefficientRows = readJson("data/generated/coefficient-rows.json").rows;

const supplementalEffectRows = effectRows.filter((row) => row.id.startsWith("effect:hoyowiki-effect:"));
const supplementalEffectSources = sourceRows.filter((row) => row.id.startsWith("source:hoyowiki-effect:"));
const gameDbCoefficientRows = coefficientRows.filter((row) => row.id.startsWith("coefficient:game-db:"));
const gameDbCoefficientSources = sourceRows.filter((row) => row.id.startsWith("source:coefficient:"));

const rowByEntryPageId = new Map(
  status.rows
    .filter((row) => row.identifiers?.hoyowikiEntryPageId)
    .map((row) => [String(row.identifiers.hoyowikiEntryPageId), row]),
);
const supplementalEffectCharacterIds = [...new Set(
  supplementalEffectRows
    .map((row) => rowByEntryPageId.get(String(row.effectProviderId))?.characterId)
    .filter(Boolean),
)];

const autoMatchTargets = new Set(["PlayerBoy_40", "Gilgamesh_00", "TohsakaRin_00", "HimekoNova_00"]);
const autoMatchRows = status.rows
  .filter((row) => autoMatchTargets.has(row.characterId))
  .map((row) => ({
    characterId: row.characterId,
    displayName: row.displayName,
    coefficientRows: row.coefficientRows,
    effectRows: row.effectRows,
    missingItems: row.missingItems,
    applied: row.coefficientRows > 0,
  }));
const autoMatchAppliedRows = autoMatchRows.filter((row) => row.applied);

const reinforcedCharacterIds = [...new Set([
  ...supplementalEffectCharacterIds,
  ...autoMatchAppliedRows.map((row) => row.characterId),
])];

const readinessBefore = summarizeReadiness(previousStatus?.summary);
const readinessAfter = summarizeReadiness(status.summary);

const report = {
  generatedBy: "tools/analyze_source_backed_supplements.mjs",
  reinforcedCharacters: reinforcedCharacterIds.length,
  reinforcedEffectRows: supplementalEffectRows.length,
  supplementalEffectSourceRows: supplementalEffectSources.length,
  designDataCoefficientRows: gameDbCoefficientRows.length,
  designDataCoefficientSourceRows: gameDbCoefficientSources.length,
  autoMatchApplied: autoMatchAppliedRows.length,
  autoMatchCandidatesRemaining: status.summary.autoMatchPossible,
  hoyowikiFilledItems: supplementalEffectRows.length,
  designDataFilledItems: gameDbCoefficientRows.length,
  curatedSourceRemaining: status.summary.curatedSourceRequired,
  stillBlockedCharacters: status.summary.blocked,
  stillBlockedRows: status.summary.blockedRows,
  readinessBefore,
  readinessAfter,
  readinessDelta: {
    ready: delta(readinessAfter.ready, readinessBefore.ready),
    partial: delta(readinessAfter.partial, readinessBefore.partial),
    blocked: delta(readinessAfter.blocked, readinessBefore.blocked),
  },
  supplementalEffectCharacters: supplementalEffectCharacterIds,
  autoMatchRows,
  supplementalEffectRowsByTargetScope: countBy(supplementalEffectRows, (row) => row.targetScope ?? "unknown"),
  supplementalEffectRowsByStat: countBy(supplementalEffectRows, (row) => row.stat ?? "unknown"),
  failureReasonCounts: status.failureReasonCounts,
  optionalMissingCounts: status.optionalMissingCounts,
  requiredMissingCounts: status.requiredMissingCounts,
};

writeJson("reports/extraction/source-backed-supplement-report.json", report);
writeReport("reports/extraction/source-backed-supplement-report.md", [
  "# Source Backed Supplement Report",
  "",
  "Generated by `node tools/analyze_source_backed_supplements.mjs`.",
  "",
  "No generated JSON was manually edited. Rows are produced by adapters from source-backed snapshots.",
  "",
  "## Summary",
  "",
  `- reinforcedCharacters: ${report.reinforcedCharacters}`,
  `- reinforcedEffectRows: ${report.reinforcedEffectRows}`,
  `- autoMatchApplied: ${report.autoMatchApplied}`,
  `- autoMatchCandidatesRemaining: ${report.autoMatchCandidatesRemaining}`,
  `- hoyowikiFilledItems: ${report.hoyowikiFilledItems}`,
  `- designDataFilledItems: ${report.designDataFilledItems}`,
  `- curatedSourceRemaining: ${report.curatedSourceRemaining}`,
  `- stillBlockedCharacters: ${report.stillBlockedCharacters}`,
  `- stillBlockedRows: ${report.stillBlockedRows}`,
  "",
  "## Readiness Change",
  "",
  `- before: ready ${readinessBefore.ready} / partial ${readinessBefore.partial} / blocked ${readinessBefore.blocked}`,
  `- after: ready ${readinessAfter.ready} / partial ${readinessAfter.partial} / blocked ${readinessAfter.blocked}`,
  `- delta: ready ${report.readinessDelta.ready} / partial ${report.readinessDelta.partial} / blocked ${report.readinessDelta.blocked}`,
  "",
  "## Auto Match",
  "",
  ...autoMatchRows.map((row) => `- ${row.characterId}: applied=${row.applied}, coefficientRows=${row.coefficientRows}, effectRows=${row.effectRows}, missingItems=${row.missingItems.join(", ") || "none"}`),
  "",
  "## HoyoWiki Supplemental Effect Characters",
  "",
  ...supplementalEffectCharacterIds.map((characterId) => `- ${characterId}`),
  "",
  "## HoyoWiki Effect Target Scopes",
  "",
  ...Object.entries(report.supplementalEffectRowsByTargetScope).map(([key, value]) => `- ${key}: ${value}`),
  "",
  "## HoyoWiki Effect Stats",
  "",
  ...Object.entries(report.supplementalEffectRowsByStat).map(([key, value]) => `- ${key}: ${value}`),
  "",
  "## Current Missing Counts",
  "",
  "- required:",
  ...Object.entries(report.requiredMissingCounts).map(([key, value]) => `  - ${key}: ${value}`),
  "- optional:",
  ...Object.entries(report.optionalMissingCounts).map(([key, value]) => `  - ${key}: ${value}`),
  "- failureReason:",
  ...Object.entries(report.failureReasonCounts).map(([key, value]) => `  - ${key}: ${value}`),
  "",
]);

console.log(JSON.stringify({
  reinforcedCharacters: report.reinforcedCharacters,
  reinforcedEffectRows: report.reinforcedEffectRows,
  autoMatchApplied: report.autoMatchApplied,
  readinessBefore,
  readinessAfter,
}, null, 2));
