import fs from "node:fs";
import path from "node:path";

const missingAnalysis = JSON.parse(fs.readFileSync("reports/extraction/missing-match-analysis.json", "utf8"));
const status = JSON.parse(fs.readFileSync("data/generated/extraction-status.json", "utf8"));
const effects = JSON.parse(fs.readFileSync("data/generated/effect-rows.json", "utf8")).rows;
const identity = JSON.parse(fs.readFileSync("data/generated/character-identity.json", "utf8"));

const statusById = new Map(status.rows.map((row) => [row.characterId, row]));
const identityById = new Map(identity.rows.map((row) => [row.characterId, row]));

function writeReport(relativePath, lines) {
  fs.mkdirSync(path.dirname(relativePath), { recursive: true });
  fs.writeFileSync(relativePath, `${lines.join("\n")}\n`, "utf8");
}

function countBy(rows, keyFn) {
  return rows.reduce((counts, row) => {
    const key = keyFn(row);
    counts[key] = (counts[key] ?? 0) + 1;
    return counts;
  }, {});
}

function list(values) {
  return values.length ? values.map((value) => `  - ${value}`) : ["  - none"];
}

const autoCandidates = missingAnalysis.rows.flatMap((row) => (
  row.missingDiagnostics
    .filter((item) => item.autoMatchPossible)
    .map((item) => {
      const statusRow = statusById.get(row.characterId);
      const identityRow = identityById.get(row.characterId);
      const closest = new Set(item.closestCandidates.map(String));
      const checks = {
        stableCharacterId: closest.has(row.characterId),
        internalId: statusRow?.internalId != null && closest.has(String(statusRow.internalId)),
        internalName: statusRow?.internalName != null && closest.has(String(statusRow.internalName)),
        entryPageId: statusRow?.identifiers?.hoyowikiEntryPageId != null && closest.has(String(statusRow.identifiers.hoyowikiEntryPageId)),
        coefficientAvatar: statusRow?.identifiers?.coefficientAvatar != null && closest.has(String(statusRow.identifiers.coefficientAvatar)),
        coefficientAvatarId: statusRow?.identifiers?.coefficientAvatarId != null && closest.has(String(statusRow.identifiers.coefficientAvatarId)),
        effectAvatar: statusRow?.identifiers?.effectAvatar != null && closest.has(String(statusRow.identifiers.effectAvatar)),
      };
      return {
        characterId: row.characterId,
        displayName: row.displayName,
        missingType: item.missingType,
        attemptedSources: item.attemptedSources,
        closestCandidates: item.closestCandidates,
        checks,
        connected: Object.values(checks).some(Boolean),
        requiredIdentityKeys: {
          characterId: row.characterId,
          internalId: statusRow?.internalId ?? identityRow?.internalId ?? null,
          internalName: statusRow?.internalName ?? identityRow?.internalName ?? null,
          entryPageId: statusRow?.identifiers?.hoyowikiEntryPageId ?? identityRow?.identifiers?.hoyowikiEntryPageId ?? null,
          avatarId: statusRow?.identifiers?.coefficientAvatarId ?? identityRow?.identifiers?.coefficientAvatarId ?? null,
          avatar: statusRow?.identifiers?.coefficientAvatar ?? identityRow?.identifiers?.coefficientAvatar ?? null,
        },
        whyCandidate: item.failureReason === "source_exists_but_id_mismatch"
          ? "closestCandidates include a stable identity/id candidate, but generated rows did not join to this character."
          : "closestCandidates include a HoyoWiki entryPageId candidate, but generated skill rows are absent.",
      };
    })
));

writeReport("reports/extraction/auto-match-verification.md", [
  "# Auto Match Verification",
  "",
  "Generated by `node tools/analyze_auto_dynamic.mjs`.",
  "",
  "No automatic matching was applied. This report only verifies whether candidate ids can be connected to stable identity keys.",
  "",
  `- candidates: ${autoCandidates.length}`,
  `- connectedCandidates: ${autoCandidates.filter((item) => item.connected).length}`,
  "",
  ...autoCandidates.flatMap((item) => [
    `## ${item.displayName}`,
    "",
    `- characterId: ${item.characterId}`,
    `- missingType: ${item.missingType}`,
    `- connectedCandidate: ${item.connected}`,
    `- whyCandidate: ${item.whyCandidate}`,
    "- attemptedSources:",
    ...list(item.attemptedSources),
    "- closestCandidates:",
    ...list(item.closestCandidates),
    "- connectionChecks:",
    ...Object.entries(item.checks).map(([key, value]) => `  - ${key}: ${value}`),
    "- requiredIdentityKeys:",
    ...Object.entries(item.requiredIdentityKeys).map(([key, value]) => `  - ${key}: ${value ?? "missing"}`),
    "- applied: false",
    "",
  ]),
]);

const effectTraceRows = missingAnalysis.rows
  .map((row) => {
    const diagnostics = row.missingDiagnostics.filter((item) => ["missing_effect_trace", "effect_rows_zero"].includes(item.missingType));
    if (!diagnostics.length) return null;
    const statusRow = statusById.get(row.characterId);
    let actionType = "curated_source_required";
    if ((statusRow?.sourceCounts?.effectCandidates ?? 0) > 0 && row.effectRows === 0) actionType = "character_identity_id_mismatch";
    else if (statusRow?.sourceAvailability?.skillText) actionType = "hoyowiki_source_parser_not_implemented";
    else if (statusRow?.identifiers?.hoyowikiEntryPageId) actionType = "source_not_loaded";
    return {
      characterId: row.characterId,
      displayName: row.displayName,
      actionType,
      mergedMissingTypes: diagnostics.map((item) => item.missingType),
      sourceAvailability: statusRow?.sourceAvailability ?? {},
      sourceCounts: statusRow?.sourceCounts ?? {},
      identifiers: statusRow?.identifiers ?? {},
      closestCandidates: diagnostics[0].closestCandidates,
      nextAction: actionType === "hoyowiki_source_parser_not_implemented"
        ? "Extend source-backed effect extraction from loaded HoyoWiki skill/eidolon text."
        : actionType === "source_not_loaded"
          ? "Load or refresh source text for the candidate entryPageId before parser work."
          : actionType === "character_identity_id_mismatch"
            ? "Fix identity/id join only after reviewing candidate mapping; do not infer values."
            : "Create curated source only after proving no parser/source path can supply the effect trace.",
    };
  })
  .filter(Boolean);
const effectTraceCounts = countBy(effectTraceRows, (row) => row.actionType);

writeReport("reports/extraction/effect-trace-action-plan.md", [
  "# Effect Trace Action Plan",
  "",
  "Generated by `node tools/analyze_auto_dynamic.mjs`.",
  "",
  "`missing_effect_trace` and `effect_rows_zero` are merged per character when they share the same root cause.",
  "",
  "## Summary",
  "",
  `- dedupedCharacters: ${effectTraceRows.length}`,
  ...["hoyowiki_source_parser_not_implemented", "source_not_loaded", "curated_source_required", "character_identity_id_mismatch"].map((key) => `- ${key}: ${effectTraceCounts[key] ?? 0}`),
  "",
  "## Character Rows",
  "",
  ...effectTraceRows.flatMap((row) => [
    `### ${row.displayName}`,
    "",
    `- characterId: ${row.characterId}`,
    `- actionType: ${row.actionType}`,
    `- mergedMissingTypes: ${row.mergedMissingTypes.join(", ")}`,
    `- skillTextLoaded: ${row.sourceAvailability.skillText}`,
    `- effectCandidateCount: ${row.sourceCounts.effectCandidates ?? 0}`,
    `- entryPageId: ${row.identifiers.hoyowikiEntryPageId ?? "missing"}`,
    "- closestCandidates:",
    ...list(row.closestCandidates),
    `- nextAction: ${row.nextAction}`,
    "",
  ]),
]);

function previousDynamicType(effect) {
  const trace = String(effect.sourceTrace ?? "").toLowerCase();
  const stat = String(effect.stat ?? "").toLowerCase();
  if (trace.includes("debuffcount")) return "debuff count";
  if (trace.includes("stack") || trace.includes("stacks") || trace.includes("nobility") || trace.includes("ashenroast") || trace.includes("overcap")) return "stack count";
  if (stat === "speed" || trace.includes(":speed")) return "speed condition";
  if (trace.includes("sourcecombatatkratio") || trace.includes("selfenhancedskill") || ["followdamage", "ultimatedamage", "basicdamage", "combatskilldamage"].includes(stat)) return "attack type condition";
  if (effect.minEidolon != null || /:e[1-6]:/i.test(String(effect.sourceTrace ?? ""))) return "eidolon condition";
  if (trace.includes("other-nihility") || trace.includes("no-other-nihility") || trace.includes("party") || trace.includes("ally") || trace.includes("allies")) return "party condition";
  return "unknown";
}

function dynamicUnknownSubtype(effect) {
  const trace = String(effect.sourceTrace ?? "").toLowerCase();
  if (trace.includes("debuffcount")) return "enemy debuff count";
  if (trace.includes("stack") || trace.includes("stacks") || trace.includes("nobility") || trace.includes("ashenroast") || trace.includes("overcap")) return "stack condition";
  if (trace.includes("sourcecombatatkratio") || trace.includes("targetatkratio") || trace.includes("source-atk") || trace.includes("atk-threshold") || trace.includes("breakeffect")) return "source stat ratio";
  if (trace.includes("level") || trace.includes("fixed")) return "level-scaled value";
  if (effect.minEidolon != null || /:e[1-6]:/i.test(String(effect.sourceTrace ?? ""))) return "eidolon condition";
  if (trace.includes("basicattack") || trace.includes("selfenhancedskill") || ["followDamage", "ultimateDamage", "basicDamage", "combatSkillDamage"].includes(effect.stat)) return "attack type condition";
  return "parser type unresolved";
}

const dynamicUnknownRows = effects
  .filter((effect) => effect.valueMode === "dynamic_formula" && previousDynamicType(effect) === "unknown")
  .map((effect) => ({ ...effect, subtype: dynamicUnknownSubtype(effect) }));
const dynamicUnknownCounts = countBy(dynamicUnknownRows, (effect) => effect.subtype);

writeReport("reports/extraction/dynamic-unknown-breakdown.md", [
  "# Dynamic Formula Unknown Breakdown",
  "",
  "Generated by `node tools/analyze_auto_dynamic.mjs`.",
  "",
  "No dynamic_formula resolver was implemented. This report only breaks down the 78 rows previously classified as `unknown` in the dynamic formula priority report.",
  "",
  "## Summary",
  "",
  `- dynamicUnknownRows: ${dynamicUnknownRows.length}`,
  ...["level-scaled value", "source stat ratio", "stack condition", "enemy debuff count", "attack type condition", "eidolon condition", "parser type unresolved"].map((key) => `- ${key}: ${dynamicUnknownCounts[key] ?? 0}`),
  "",
  "## Rows",
  "",
  ...dynamicUnknownRows.flatMap((effect) => [
    `### ${effect.id}`,
    "",
    `- characterId: ${effect.effectProviderId}`,
    `- subtype: ${effect.subtype}`,
    `- stat: ${effect.stat}`,
    `- effectType: ${effect.effectType}`,
    `- rawValue: ${effect.rawValue}`,
    `- minEidolon: ${effect.minEidolon ?? "none"}`,
    `- sourceTrace: ${effect.sourceTrace}`,
    "",
  ]),
]);

console.log(JSON.stringify({
  autoMatchConnected: autoCandidates.filter((item) => item.connected).length,
  effectTraceCounts,
  dynamicUnknownCounts,
}, null, 2));
