import fs from "node:fs";
import path from "node:path";

const fixturesDir = "data/legacy-reference/diff-fixtures";
const jsonReportPath = "reports/diff/legacy-v2-diff.json";
const mdReportPath = "reports/diff/legacy-v2-diff-report.md";

function readFixture(fileName) {
  return JSON.parse(fs.readFileSync(path.join(fixturesDir, fileName), "utf8"));
}

const fixtureFiles = fs.readdirSync(fixturesDir).filter((fileName) => fileName.endsWith(".json")).sort();
const fixtures = fixtureFiles.map(readFixture);
const expected = [];
const unexpected = [];

for (const fixture of fixtures) {
  const row = {
    id: fixture.id,
    legacyReference: fixture.legacyReference,
    v2Reference: fixture.v2Reference,
    category: fixture.expectedDifferenceCategory ?? "uncategorized",
    reason: fixture.reason ?? "",
  };
  if (fixture.expectedDifferenceCategory) expected.push(row);
  else unexpected.push(row);
}

const report = {
  version: 1,
  generatedBy: "tools/compare_legacy_and_v2.mjs",
  counts: {
    fixtures: fixtures.length,
    expected: expected.length,
    unexpected: unexpected.length,
  },
  expected,
  unexpected,
};

fs.writeFileSync(jsonReportPath, `${JSON.stringify(report, null, 2)}\n`, "utf8");

const lines = [
  "# Legacy v2 Diff Report",
  "",
  "Generated by `npm.cmd run diff:legacy`.",
  "",
  `- fixtures: ${report.counts.fixtures}`,
  `- expected: ${report.counts.expected}`,
  `- unexpected: ${report.counts.unexpected}`,
  "",
  "## Expected Differences",
  "",
  "| fixture | category | reason |",
  "| --- | --- | --- |",
  ...expected.map((row) => `| ${row.id} | ${row.category} | ${row.reason} |`),
  "",
  "## Unexpected Differences",
  "",
  ...(unexpected.length ? unexpected.map((row) => `- ${row.id}: ${row.category}`) : ["- none"]),
];
fs.writeFileSync(mdReportPath, `${lines.join("\n")}\n`, "utf8");

console.log(`legacy diff ok: fixtures=${report.counts.fixtures}, expected=${report.counts.expected}, unexpected=${report.counts.unexpected}`);
