import fs from "node:fs";
import path from "node:path";
import { listAdapters } from "../src/adapters/adapter-registry.js";
import { assertValidAdapterResult } from "../src/adapters/adapter-validator.js";

const generatedDir = "data/generated";
const reportPath = "reports/adapter/adapter-run-report.md";

function writeJson(relativePath, value) {
  fs.writeFileSync(relativePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

const adapters = listAdapters();
const sourceRows = [];
const effectRows = [];
const coefficientRows = [];
const blockedRows = [];
const adapterReports = [];

for (const adapter of adapters) {
  const input = adapter.load({});
  const output = adapter.normalize(input, {});
  const report = adapter.report({ output }, {});
  assertValidAdapterResult({
    adapterId: adapter.adapterId,
    sourceKind: adapter.sourceKind,
    input: null,
    output,
    report,
  });
  sourceRows.push(...output.sourceRows);
  effectRows.push(...output.effectRows);
  coefficientRows.push(...output.coefficientRows);
  blockedRows.push(...output.blockedRows);
  adapterReports.push({ adapterId: adapter.adapterId, sourceKind: adapter.sourceKind, counts: report.counts, warnings: report.warnings });
}

fs.mkdirSync(generatedDir, { recursive: true });
writeJson(path.join(generatedDir, "source-rows.json"), {
  version: 1,
  generatedBy: "tools/run_adapters.mjs",
  rows: sourceRows,
});
writeJson(path.join(generatedDir, "effect-rows.json"), {
  version: 1,
  generatedBy: "tools/run_adapters.mjs",
  rows: effectRows,
});
writeJson(path.join(generatedDir, "coefficient-rows.json"), {
  version: 1,
  generatedBy: "tools/run_adapters.mjs",
  rows: coefficientRows,
});

const reportLines = [
  "# Adapter Run Report",
  "",
  "Generated by `npm.cmd run data:adapters`.",
  "",
  `- adapters: ${adapters.length}`,
  `- sourceRows: ${sourceRows.length}`,
  `- effectRows: ${effectRows.length}`,
  `- coefficientRows: ${coefficientRows.length}`,
  `- blockedRows: ${blockedRows.length}`,
  "",
  "| adapter | sourceKind | sourceRows | effectRows | coefficientRows | blockedRows | warnings |",
  "| --- | --- | ---: | ---: | ---: | ---: | ---: |",
  ...adapterReports.map((report) => `| ${report.adapterId} | ${report.sourceKind} | ${report.counts.sourceRows} | ${report.counts.effectRows} | ${report.counts.coefficientRows} | ${report.counts.blockedRows} | ${report.counts.warnings} |`),
  "",
];
fs.writeFileSync(reportPath, `${reportLines.join("\n")}\n`, "utf8");

console.log(`adapter run ok: adapters=${adapters.length}, sourceRows=${sourceRows.length}, effectRows=${effectRows.length}, coefficientRows=${coefficientRows.length}`);
