import fs from "node:fs";
import path from "node:path";
import { buildCharacterIdentityDataset, validateCharacterIdentityDataset } from "../src/identity/character-identity.js";

const generatedPath = "data/generated/character-identity.json";
const reportPath = "reports/extraction/character-identity-report.md";

function writeJson(relativePath, value) {
  fs.mkdirSync(path.dirname(relativePath), { recursive: true });
  fs.writeFileSync(relativePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function writeText(relativePath, lines) {
  fs.mkdirSync(path.dirname(relativePath), { recursive: true });
  fs.writeFileSync(relativePath, `${lines.join("\n")}\n`, "utf8");
}

function issueRows(dataset) {
  return dataset.rows.filter((row) => row.nameReviewStatus !== "source_backed");
}

function aliasRows(dataset) {
  return dataset.rows.filter((row) => row.aliasNames.length > 0);
}

const dataset = buildCharacterIdentityDataset();
const validation = validateCharacterIdentityDataset(dataset);
if (!validation.ok) {
  throw new Error(`character identity validation failed: ${validation.errors.join("; ")}`);
}

writeJson(generatedPath, dataset);

const rowsNeedingReview = issueRows(dataset);
const rowsWithAliases = aliasRows(dataset);
const sourceOriginCounts = dataset.rows.reduce((counts, row) => {
  counts[row.sourceOrigin ?? "unknown"] = (counts[row.sourceOrigin ?? "unknown"] ?? 0) + 1;
  return counts;
}, {});

writeText(reportPath, [
  "# Character Identity Report",
  "",
  "Generated by `npm.cmd run validate:identity`.",
  "",
  "## Summary",
  "",
  `- characters: ${dataset.summary.characters}`,
  `- sourceBackedDisplayNames: ${dataset.summary.sourceBackedDisplayNames}`,
  `- sourceBackedIdentities: ${dataset.summary.sourceBackedIdentities}`,
  `- aliases: ${dataset.summary.aliases}`,
  `- rowsWithAliases: ${rowsWithAliases.length}`,
  `- rowsNeedingReview: ${rowsNeedingReview.length}`,
  "",
  "## Source Origins",
  "",
  ...Object.entries(sourceOriginCounts).sort((a, b) => a[0].localeCompare(b[0])).map(([origin, count]) => `- ${origin}: ${count}`),
  "",
  "## Alias Rows",
  "",
  ...(rowsWithAliases.length ? rowsWithAliases.map((row) => `- ${row.displayName}: aliases=[${row.aliasNames.join(", ")}]`) : ["- none"]),
  "",
  "## Rows Needing Review",
  "",
  ...(rowsNeedingReview.length ? rowsNeedingReview.map((row) => `- ${row.displayName}: displayNameSourceBacked=${row.isDisplayNameSourceBacked}, identitySourceBacked=${row.isCharacterIdentitySourceBacked}`) : ["- none"]),
  "",
  "## Contract",
  "",
  "- `displayName` must match `officialName`.",
  "- `aliasNames` are retained only for lookup/search and must not be promoted to `displayName`.",
  "- `characterId` is a stable identity key, not a localized display string.",
  "- Existing project files were read as source evidence only and were not modified.",
]);

console.log(`character identity validation ok: characters=${dataset.summary.characters}, aliases=${dataset.summary.aliases}, sourceBacked=${dataset.summary.sourceBackedDisplayNames}`);
