import fs from "node:fs";
import { CalculationStatus, SourceKind, SourceOrigin } from "../src/data-model/schemas/index.js";
import { listAdapters } from "../src/adapters/adapter-registry.js";
import { validateAdapterResult } from "../src/adapters/adapter-validator.js";

const adapters = listAdapters();
if (!adapters.length) throw new Error("adapter registry is empty");

for (const adapter of adapters) {
  const input = adapter.load({});
  const output = adapter.normalize(input, {});
  const result = {
    adapterId: adapter.adapterId,
    sourceKind: adapter.sourceKind,
    input: null,
    output,
    report: adapter.report({ output }, {}),
  };
  const validation = validateAdapterResult(result);
  if (!validation.ok) {
    throw new Error(`${adapter.adapterId} output failed validation: ${validation.errors.join("; ")}`);
  }
}

const invalidManualHintResult = {
  adapterId: "invalid-manual-hint-fixture",
  sourceKind: SourceKind.LEGACY_SNAPSHOT,
  output: {
    sourceRows: [
      {
        id: "invalid:manual-hint-ready",
        sourceOrigin: SourceOrigin.MANUAL_HINT,
        sourceKind: SourceKind.LEGACY_SNAPSHOT,
        sourcePath: "data/character-effects/character-guides.json",
        sourceRecord: "guide:invalid",
        calculationStatus: CalculationStatus.CALCULATION_READY,
      },
    ],
    effectRows: [],
    coefficientRows: [],
    blockedRows: [],
  },
  report: {
    counts: {
      sourceRows: 1,
      effectRows: 0,
      coefficientRows: 0,
      blockedRows: 0,
      warnings: 0,
      errors: 0,
    },
    warnings: [],
    errors: [],
  },
};

if (validateAdapterResult(invalidManualHintResult).ok) {
  throw new Error("invalid manual_hint adapter fixture unexpectedly passed validation");
}

function writeAdapterReport(adapterId, title) {
  const adapter = adapters.find((item) => item.adapterId === adapterId);
  if (!adapter) throw new Error(`${adapterId} adapter missing`);
  const output = adapter.normalize(adapter.load({}), {});
  const report = adapter.report({ output }, {});
  const reportLines = [
    `# ${title}`,
    "",
    "Generated by `npm.cmd run validate:adapters`.",
    "",
    `- sourceRows: ${report.counts.sourceRows}`,
    `- effectRows: ${report.counts.effectRows}`,
    `- coefficientRows: ${report.counts.coefficientRows}`,
    `- blockedRows: ${report.counts.blockedRows}`,
    `- sampledCharacters: ${(output.metadata?.sampledCharacters ?? []).join(", ")}`,
    `- skillCharactersAvailable: ${output.metadata?.skillCharactersAvailable ?? 0}`,
    ...(output.metadata?.coefficientCharactersAvailable != null ? [`- coefficientCharactersAvailable: ${output.metadata.coefficientCharactersAvailable}`] : []),
    ...(output.metadata?.baselineSnapshotAvailable != null ? [`- baselineSnapshotAvailable: ${output.metadata.baselineSnapshotAvailable === true}`] : []),
    "",
    "Warnings:",
    ...(report.warnings.length ? report.warnings.map((warning) => `- ${warning}`) : ["- none"]),
    "",
  ];
  fs.writeFileSync(`reports/adapter/${adapterId}-report.md`, `${reportLines.join("\n")}\n`, "utf8");
  return { output, report };
}

writeAdapterReport("local-json", "Local JSON Adapter Report");
writeAdapterReport("hoyowiki", "HoyoWiki Adapter Report");

console.log(`adapter validation ok: adapters=${adapters.length}, invalid_manual_hint_guard=blocked`);
