import fs from "node:fs";
import { AggregationResultFields } from "../src/calculator/aggregation-contract.js";
import { runCalculationV2 } from "../src/calculator/run-calculation-v2.js";

const ledgerPath = "data/generated/combat-ledger-sample.json";
const samplePath = "data/generated/calculation-result-sample.json";
const reportPath = "reports/calculation/aggregation-report.md";

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function writeJson(filePath, value) {
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function validateAggregationResult(result, ledgerRows) {
  const errors = [];
  for (const field of AggregationResultFields) {
    if (!(field in result)) errors.push(`missing aggregation field: ${field}`);
  }
  const expectedIds = ledgerRows.map((row) => row.ledgerId);
  if (JSON.stringify(result.ledgerRowIds) !== JSON.stringify(expectedIds)) {
    errors.push("ledgerRowIds must match ledger input order");
  }
  if (result.sourceTrace?.ledgerRows !== ledgerRows.length) errors.push("sourceTrace ledgerRows mismatch");
  for (const skipped of result.skippedRows ?? []) {
    if (!skipped.ledgerId || !skipped.blockedReason) errors.push("skippedRows require ledgerId and blockedReason");
  }
  return { ok: errors.length === 0, errors };
}

function assertValidAggregationResult(result, ledgerRows, label) {
  const validation = validateAggregationResult(result, ledgerRows);
  if (!validation.ok) throw new Error(`${label} failed validation: ${validation.errors.join("; ")}`);
}

const ledgerRows = readJson(ledgerPath).rows;
const first = runCalculationV2(ledgerRows, { scenarioId: "sample", subjectId: "sample" });
const second = runCalculationV2(ledgerRows, { scenarioId: "sample", subjectId: "sample" });
if (JSON.stringify(first) !== JSON.stringify(second)) {
  throw new Error("runCalculationV2 is not deterministic for the same ledger input");
}
assertValidAggregationResult(first, ledgerRows, "sample aggregation result");
writeJson(samplePath, {
  version: 1,
  generatedBy: "tools/validate_aggregation.mjs",
  result: first,
});

const reportLines = [
  "# Aggregation Report",
  "",
  "Generated by `npm.cmd run validate:aggregation`.",
  "",
  "## Sample Result",
  "",
  `- ledgerRows: ${ledgerRows.length}`,
  `- usedRows: ${first.sourceTrace.usedRows}`,
  `- blockedRows: ${first.sourceTrace.blockedRows}`,
  `- statTotals: ${Object.keys(first.statTotals).length}`,
  `- damageModifiers: ${Object.keys(first.damageModifiers).length}`,
  `- enemyDebuffs: ${Object.keys(first.enemyDebuffs).length}`,
  `- skippedRows: ${first.skippedRows.length}`,
  "",
  "## Guardrails",
  "",
  "- Result ledgerRowIds must match the ledger input order.",
  "- The same ledger input must return the same aggregation result.",
  "- Calculation result is produced from ledger rows and aggregation modules only.",
  "",
  "## Deferred",
  "",
  "- UI shell wiring is deferred to Phase 13.",
  "- Legacy comparison is deferred to Phase 16.",
];
fs.writeFileSync(reportPath, `${reportLines.join("\n")}\n`, "utf8");

console.log(`aggregation validation ok: ledgerRows=${ledgerRows.length}, statTotals=${Object.keys(first.statTotals).length}, skippedRows=${first.skippedRows.length}, deterministic=true`);
