import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const manifestPath = path.join(root, "data", "legacy-reference", "manifest.json");
const reportPath = path.join(root, "reports", "legacy", "legacy-manifest-report.md");
const allowedPurposes = new Set([
  "adapter_input_candidate",
  "reference_only",
  "blocked_calculation_reference",
]);

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function fail(message) {
  throw new Error(message);
}

function validateEntry(entry, seenIds) {
  const errors = [];
  if (!entry.id) errors.push("missing id");
  if (seenIds.has(entry.id)) errors.push(`duplicate id: ${entry.id}`);
  seenIds.add(entry.id);
  if (!entry.sourceProjectPath) errors.push("missing sourceProjectPath");
  if (!entry.snapshotPath) errors.push("missing snapshotPath");
  if (!allowedPurposes.has(entry.purpose)) errors.push(`invalid purpose: ${entry.purpose}`);
  if (entry.prohibitedRuntimeImport !== true) errors.push("prohibitedRuntimeImport must be true");
  if (!entry.calculationUse) errors.push("missing calculationUse");
  if (!entry.sourceOrigin) errors.push("missing sourceOrigin");
  if (!entry.sourceKind) errors.push("missing sourceKind");

  const snapshotAbsolutePath = path.join(root, entry.snapshotPath);
  if (!fs.existsSync(snapshotAbsolutePath)) {
    errors.push(`snapshot missing: ${entry.snapshotPath}`);
  } else {
    const stat = fs.statSync(snapshotAbsolutePath);
    if (!stat.isFile()) errors.push(`snapshot is not file: ${entry.snapshotPath}`);
    if (Number.isFinite(entry.bytes) && entry.bytes !== stat.size) {
      errors.push(`byte size mismatch: expected ${entry.bytes}, got ${stat.size}`);
    }
  }
  return errors;
}

const manifest = readJson(manifestPath);
if (manifest.schemaVersion !== 1) fail("manifest schemaVersion must be 1");
if (manifest.policy?.prohibitedRuntimeImport !== true) fail("manifest policy must prohibit runtime import");
if (manifest.policy?.allowCalculationSourcePromotion !== false) fail("manifest policy must block direct calculation source promotion");
if (!Array.isArray(manifest.entries) || manifest.entries.length === 0) fail("manifest entries are missing");

const seenIds = new Set();
const rows = manifest.entries.map((entry) => {
  const errors = validateEntry(entry, seenIds);
  return {
    id: entry.id,
    purpose: entry.purpose,
    snapshotPath: entry.snapshotPath,
    sourceOrigin: entry.sourceOrigin,
    bytes: entry.bytes,
    ok: errors.length === 0,
    errors,
  };
});

const failedRows = rows.filter((row) => !row.ok);
if (failedRows.length) {
  for (const row of failedRows) {
    console.error(`${row.id}: ${row.errors.join("; ")}`);
  }
  fail(`legacy manifest validation failed: ${failedRows.length} entries`);
}

const lines = [
  "# Legacy Manifest Report",
  "",
  "Generated by `npm.cmd run validate:legacy`.",
  "",
  `- manifest: \`data/legacy-reference/manifest.json\``,
  `- entries: ${rows.length}`,
  `- failed: ${failedRows.length}`,
  `- prohibitedRuntimeImport: ${manifest.policy.prohibitedRuntimeImport}`,
  `- allowCalculationSourcePromotion: ${manifest.policy.allowCalculationSourcePromotion}`,
  "",
  "| id | purpose | sourceOrigin | bytes | snapshot |",
  "| --- | --- | --- | ---: | --- |",
  ...rows.map((row) => `| \`${row.id}\` | ${row.purpose} | ${row.sourceOrigin} | ${row.bytes ?? "-"} | \`${row.snapshotPath}\` |`),
  "",
];

fs.writeFileSync(reportPath, `${lines.join("\n")}\n`, "utf8");
console.log(`legacy manifest validation ok: entries=${rows.length}, report=reports/legacy/legacy-manifest-report.md`);
