import fs from "node:fs";
import { BlockedReason, CalculationStatus, TargetScope } from "../src/data-model/schemas/index.js";
import { isKnownEffectType, isKnownValueMode } from "../src/effect-engine/effect-taxonomy.js";
import { normalizeEffect, normalizeEffects } from "../src/effect-engine/normalize-effects.js";

const canonicalDatasetPath = "data/generated/extraction-canonical-dataset.json";
const normalizedPath = "data/generated/normalized-effect-rows.json";
const reportPath = "reports/effect-engine/normalization-report.md";

function readJson(path) {
  return JSON.parse(fs.readFileSync(path, "utf8"));
}

function writeJson(path, value) {
  fs.writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function countBy(rows, field) {
  return rows.reduce((counts, row) => {
    const value = row?.[field] ?? "none";
    counts[value] = (counts[value] ?? 0) + 1;
    return counts;
  }, {});
}

function validateNormalizedRows(rows) {
  const errors = [];
  for (const row of rows) {
    if (!row.id) errors.push("normalized row missing id");
    if (!row.effectRowId) errors.push(`${row.id}: missing effectRowId`);
    if (!row.sourceId) errors.push(`${row.id}: missing sourceId`);
    if (!row.effectType || !isKnownEffectType(row.effectType)) errors.push(`${row.id}: unknown effectType must be blocked`);
    if (!row.valueMode || !isKnownValueMode(row.valueMode)) errors.push(`${row.id}: unknown valueMode must be blocked`);
    if (!row.targetScope || row.targetScope === TargetScope.UNKNOWN) errors.push(`${row.id}: missing targetScope`);
    if (Object.hasOwn(row, "resolvedValue")) errors.push(`${row.id}: resolvedValue must not be produced during normalization`);

    const unknownEffectType = !isKnownEffectType(row.effectType);
    const unknownValueMode = !isKnownValueMode(row.valueMode);
    const missingTargetScope = !row.targetScope || row.targetScope === TargetScope.UNKNOWN;
    if ((unknownEffectType || unknownValueMode || missingTargetScope) && row.calculationStatus === CalculationStatus.CALCULATION_READY) {
      errors.push(`${row.id}: unknown taxonomy must not be calculation_ready`);
    }
    if (row.calculationStatus === CalculationStatus.BLOCKED && !row.blockedReason) {
      errors.push(`${row.id}: blocked row requires blockedReason`);
    }
  }
  return { ok: errors.length === 0, errors };
}

function assertValidNormalizedRows(rows, label) {
  const result = validateNormalizedRows(rows);
  if (!result.ok) throw new Error(`${label} failed validation: ${result.errors.join("; ")}`);
}

const canonicalDataset = readJson(canonicalDatasetPath);
const rows = normalizeEffects(canonicalDataset.rows.effectRows);
writeJson(normalizedPath, {
  version: 1,
  generatedBy: "tools/validate_effect_normalization.mjs",
  rows,
});
assertValidNormalizedRows(rows, "generated normalized effects");

const unknownValueRow = normalizeEffect({
  id: "fixture:unknown-value-mode",
  sourceId: "source:fixture",
  sourceOrigin: "raw_source",
  effectType: "buff",
  stat: "atkRatio",
  valueMode: "unknown_value_mode",
  effectProviderId: "fixture",
  effectTargetPolicy: "self",
  calculationSubjectPolicy: "self",
  calculationStatus: CalculationStatus.CALCULATION_READY,
});
if (unknownValueRow.calculationStatus !== CalculationStatus.BLOCKED || unknownValueRow.blockedReason !== BlockedReason.VALUE_MODE_UNKNOWN) {
  throw new Error("unknown valueMode fixture was not blocked as value_mode_unknown");
}

const unknownEffectRow = normalizeEffect({
  id: "fixture:unknown-effect-type",
  sourceId: "source:fixture",
  sourceOrigin: "raw_source",
  effectType: "unknown_effect_type",
  stat: "atkRatio",
  valueMode: "fixed",
  effectProviderId: "fixture",
  effectTargetPolicy: "self",
  calculationSubjectPolicy: "self",
  calculationStatus: CalculationStatus.CALCULATION_READY,
});
if (unknownEffectRow.calculationStatus !== CalculationStatus.BLOCKED) {
  throw new Error("unknown effectType fixture was not blocked");
}

const bypassRows = [{
  ...unknownValueRow,
  calculationStatus: CalculationStatus.CALCULATION_READY,
  blockedReason: null,
}];
if (validateNormalizedRows(bypassRows).ok) {
  throw new Error("unknown valueMode calculation-ready bypass unexpectedly passed validation");
}

const statusCounts = countBy(rows, "calculationStatus");
const blockedReasonCounts = countBy(rows.filter((row) => row.blockedReason), "blockedReason");
const targetScopeCounts = countBy(rows, "targetScope");
const valueModeCounts = countBy(rows, "valueMode");

const reportLines = [
  "# Effect Normalization Report",
  "",
  "Generated by `npm.cmd run validate:effect-normalization`.",
  "",
  "## Normalized Rows",
  "",
  `- rows: ${rows.length}`,
  `- calculation_ready: ${statusCounts[CalculationStatus.CALCULATION_READY] ?? 0}`,
  `- blocked: ${statusCounts[CalculationStatus.BLOCKED] ?? 0}`,
  `- unknown valueMode guard: ${BlockedReason.VALUE_MODE_UNKNOWN}`,
  "",
  "## Target Scopes",
  "",
  ...Object.entries(targetScopeCounts).map(([key, value]) => `- ${key}: ${value}`),
  "",
  "## Value Modes",
  "",
  ...Object.entries(valueModeCounts).map(([key, value]) => `- ${key}: ${value}`),
  "",
  "## Blocked Reasons",
  "",
  ...(Object.keys(blockedReasonCounts).length ? Object.entries(blockedReasonCounts).map(([key, value]) => `- ${key}: ${value}`) : ["- none"]),
  "",
  "## Deferred",
  "",
  "- Value resolving is deferred to Phase 9.",
  "- Dedupe is deferred to Phase 10.",
  "- Calculation logic remains out of scope.",
];
fs.writeFileSync(reportPath, `${reportLines.join("\n")}\n`, "utf8");

console.log(`effect normalization validation ok: rows=${rows.length}, ready=${statusCounts[CalculationStatus.CALCULATION_READY] ?? 0}, blocked=${statusCounts[CalculationStatus.BLOCKED] ?? 0}, unknown_value_guard=blocked`);
