import fs from "node:fs";
import { buildCombatLedger, RequiredCombatLedgerFields } from "../src/effect-engine/build-combat-ledger.js";

const samplePath = "data/generated/combat-ledger-sample.json";
const reportPath = "reports/calculation/combat-ledger-report.md";

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function writeJson(filePath, value) {
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function validateCombatLedgerRows(rows) {
  const errors = [];
  for (const row of rows) {
    for (const field of RequiredCombatLedgerFields) {
      if (!(field in row)) errors.push(`${row.ledgerId ?? "unknown"}: missing ${field}`);
    }
    if (row.usedForCalculation) {
      if (!row.sourceId || !row.sourceRowId || !row.sourceTrace?.sourceId) errors.push(`${row.ledgerId}: used row requires source trace`);
      if (typeof row.resolvedValue !== "number") errors.push(`${row.ledgerId}: used row requires resolvedValue`);
      if (!row.canonicalEffectKey) errors.push(`${row.ledgerId}: used row requires canonicalEffectKey`);
    } else if (!row.blockedReason) {
      errors.push(`${row.ledgerId}: blocked/skipped row requires blockedReason`);
    }
  }
  return { ok: errors.length === 0, errors };
}

function assertValidCombatLedgerRows(rows, label) {
  const result = validateCombatLedgerRows(rows);
  if (!result.ok) throw new Error(`${label} failed validation: ${result.errors.join("; ")}`);
}

const dedupedEffects = readJson("data/generated/deduped-effects.json").rows;
const normalizedEffects = readJson("data/generated/normalized-effect-rows.json").rows;
const rows = buildCombatLedger(dedupedEffects, { normalizedEffects });
assertValidCombatLedgerRows(rows, "generated combat ledger");
writeJson(samplePath, {
  version: 1,
  generatedBy: "tools/validate_combat_ledger.mjs",
  rows,
});

const sourceMissingFixture = {
  ...rows.find((row) => row.usedForCalculation),
  sourceId: null,
  sourceRowId: null,
  sourceTrace: { sourceId: null },
};
if (validateCombatLedgerRows([sourceMissingFixture]).ok) {
  throw new Error("source-less used ledger row unexpectedly passed validation");
}

const usedRows = rows.filter((row) => row.usedForCalculation);
const blockedRows = rows.filter((row) => !row.usedForCalculation);
const reportLines = [
  "# Combat Ledger Report",
  "",
  "Generated by `npm.cmd run validate:combat-ledger`.",
  "",
  "## Sample Ledger",
  "",
  `- rows: ${rows.length}`,
  `- usedForCalculation: ${usedRows.length}`,
  `- blockedOrSkipped: ${blockedRows.length}`,
  "",
  "## Validation",
  "",
  "- used rows require sourceId/sourceRowId/sourceTrace.",
  "- used rows require resolvedValue.",
  "- blocked/skipped rows require blockedReason.",
  "- source-less used row fixture is blocked.",
  "",
  "## Deferred",
  "",
  "- Aggregation is deferred to Phase 12.",
  "- UI trace rendering is deferred to later UI phases.",
];
fs.writeFileSync(reportPath, `${reportLines.join("\n")}\n`, "utf8");

console.log(`combat ledger validation ok: rows=${rows.length}, used=${usedRows.length}, blocked=${blockedRows.length}, source_guard=blocked`);
