import fs from "node:fs";
import path from "node:path";
import { CalculationStatus, ValueMode } from "../src/data-model/schemas/index.js";
import { resolveValue, resolveValues } from "../src/effect-engine/resolve-values.js";

const normalizedPath = "data/generated/normalized-effect-rows.json";
const resolvedPath = "data/generated/resolved-effects.json";
const fixturesDir = "data/generated/value-resolution-fixtures";
const reportPath = "reports/effect-engine/value-resolution-report.md";

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function writeJson(filePath, value) {
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function countBy(rows, field) {
  return rows.reduce((counts, row) => {
    const value = row?.[field] ?? "none";
    counts[value] = (counts[value] ?? 0) + 1;
    return counts;
  }, {});
}

function validateResolvedEffects(rows) {
  const errors = [];
  for (const row of rows) {
    const hasResolvedValue = typeof row.resolvedValue === "number";
    const hasBlockedReason = Boolean(row.blockedReason);
    if (hasResolvedValue === hasBlockedReason) {
      errors.push(`${row.id}: must have exactly one of resolvedValue or blockedReason`);
    }
    if (!row.valueTrace || typeof row.valueTrace !== "object") errors.push(`${row.id}: missing valueTrace`);
    if (!row.dedupeKey) errors.push(`${row.id}: missing pending dedupeKey`);
    if (row.valueTrace?.resolver === "unknown" && row.calculationStatus === CalculationStatus.CALCULATION_READY) {
      errors.push(`${row.id}: unknown valueMode must not be calculation_ready`);
    }
  }
  return { ok: errors.length === 0, errors };
}

function assertValidResolvedEffects(rows, label) {
  const result = validateResolvedEffects(rows);
  if (!result.ok) throw new Error(`${label} failed validation: ${result.errors.join("; ")}`);
}

function fixtureEffect(overrides = {}) {
  return {
    id: "normalized:fixture",
    effectRowId: "fixture:effect",
    sourceId: "source:fixture",
    sourceOrigin: "raw_source",
    effectProviderId: "fixture",
    stat: "atkRatio",
    rawValue: 0.12,
    effectType: "buff",
    targetScope: "self",
    attackType: "support",
    valueMode: ValueMode.FIXED,
    calculationStatus: CalculationStatus.CALCULATION_READY,
    ...overrides,
  };
}

const normalizedRows = readJson(normalizedPath).rows;
const resolvedRows = resolveValues(normalizedRows);
assertValidResolvedEffects(resolvedRows, "generated resolved effects");
writeJson(resolvedPath, {
  version: 1,
  generatedBy: "tools/validate_value_resolution.mjs",
  rows: resolvedRows,
});

const fixtureCases = [
  {
    fileName: "fixed-success.json",
    input: fixtureEffect({ valueMode: ValueMode.FIXED, rawValue: 0.2 }),
    options: {},
  },
  {
    fileName: "skill-level-missing.json",
    input: fixtureEffect({ valueMode: ValueMode.SKILL_LEVEL_SCALED }),
    options: { context: { skillLevel: null } },
  },
  {
    fileName: "eidolon-missing.json",
    input: fixtureEffect({ valueMode: ValueMode.EIDOLON_ADJUSTED }),
    options: { context: { eidolon: null } },
  },
  {
    fileName: "superimposition-missing.json",
    input: fixtureEffect({ valueMode: ValueMode.SUPERIMPOSITION_SCALED }),
    options: { context: { superimposition: null } },
  },
  {
    fileName: "dynamic-unsupported.json",
    input: fixtureEffect({ valueMode: ValueMode.DYNAMIC_FORMULA }),
    options: {},
  },
  {
    fileName: "unknown-value-mode.json",
    input: fixtureEffect({ valueMode: "unknown_fixture_mode" }),
    options: {},
  },
];

fs.mkdirSync(fixturesDir, { recursive: true });
const fixtureResults = fixtureCases.map((fixtureCase) => {
  const output = resolveValue(fixtureCase.input, fixtureCase.options);
  assertValidResolvedEffects([output], fixtureCase.fileName);
  const payload = {
    version: 1,
    generatedBy: "tools/validate_value_resolution.mjs",
    input: fixtureCase.input,
    options: fixtureCase.options,
    output,
  };
  writeJson(path.join(fixturesDir, fixtureCase.fileName), payload);
  return { fileName: fixtureCase.fileName, output };
});

const unknownOutput = fixtureResults.find((item) => item.fileName === "unknown-value-mode.json")?.output;
if (!unknownOutput?.blockedReason || unknownOutput.calculationStatus === CalculationStatus.CALCULATION_READY) {
  throw new Error("unknown valueMode fixture unexpectedly entered calculation");
}

const statusCounts = countBy(resolvedRows, "calculationStatus");
const blockedReasonCounts = countBy(resolvedRows.filter((row) => row.blockedReason), "blockedReason");

const reportLines = [
  "# Value Resolution Report",
  "",
  "Generated by `npm.cmd run validate:value-resolution`.",
  "",
  "## Resolved Effects",
  "",
  `- rows: ${resolvedRows.length}`,
  `- calculation_ready: ${statusCounts[CalculationStatus.CALCULATION_READY] ?? 0}`,
  `- blocked: ${statusCounts[CalculationStatus.BLOCKED] ?? 0}`,
  "",
  "## Blocked Reasons",
  "",
  ...(Object.keys(blockedReasonCounts).length ? Object.entries(blockedReasonCounts).map(([key, value]) => `- ${key}: ${value}`) : ["- none"]),
  "",
  "## Fixtures",
  "",
  ...fixtureResults.map((item) => `- ${item.fileName}: ${item.output.calculationStatus}${item.output.blockedReason ? ` / ${item.output.blockedReason}` : ""}`),
  "",
  "## Deferred",
  "",
  "- Dedupe is deferred to Phase 10.",
  "- Aggregation is deferred to Phase 12.",
  "- Unknown value modes remain blocked.",
];
fs.writeFileSync(reportPath, `${reportLines.join("\n")}\n`, "utf8");

console.log(`value resolution validation ok: rows=${resolvedRows.length}, ready=${statusCounts[CalculationStatus.CALCULATION_READY] ?? 0}, blocked=${statusCounts[CalculationStatus.BLOCKED] ?? 0}, fixtures=${fixtureResults.length}, unknown_guard=blocked`);
