import fs from "node:fs";

const checks = [
  { id: "dist-index", path: "dist/index.html", pattern: /<div\s+id="root"\s*>\s*<\/div>|<div\s+id="root"\s*><\/div>/ },
  { id: "route-home", path: "src/app/route-config.js", pattern: /path: "\/"/ },
  { id: "route-extraction", path: "src/app/route-config.js", pattern: /path: "\/extraction"/ },
  { id: "route-extraction-detail", path: "src/app/route-config.js", pattern: /\/extraction\/:characterId/ },
  { id: "route-ledger", path: "src/app/route-config.js", pattern: /path: "\/ledger"/ },
  { id: "generated-extraction-status", path: "data/generated/extraction-status.json", pattern: /"summary"/ },
  { id: "generated-ledger", path: "data/generated/combat-ledger-sample.json", pattern: /"rows"/ },
  { id: "generated-calculation", path: "data/generated/calculation-result-sample.json", pattern: /"result"/ },
];

const results = checks.map((check) => {
  const exists = fs.existsSync(check.path);
  const content = exists ? fs.readFileSync(check.path, "utf8") : "";
  const ok = exists && check.pattern.test(content);
  return { ...check, ok };
});

const failed = results.filter((result) => !result.ok);
const lines = [
  "# App Smoke Report",
  "",
  "Generated by `npm.cmd run verify:app`.",
  "",
  `- checks: ${results.length}`,
  `- passed: ${results.length - failed.length}`,
  `- failed: ${failed.length}`,
  "",
  "| check | path | status |",
  "| --- | --- | --- |",
  ...results.map((result) => `| ${result.id} | ${result.path} | ${result.ok ? "pass" : "fail"} |`),
];
fs.writeFileSync("reports/validation/app-smoke-report.md", `${lines.join("\n")}\n`, "utf8");

if (failed.length) {
  throw new Error(`app smoke failed: ${failed.map((item) => item.id).join(", ")}`);
}

console.log(`app smoke ok: checks=${results.length}`);
